Repository Monash-FIT3170/Behind-The-Veil, pull requests merged in 2024-09, with the labels that each got.

#128 bug-fix/message-same-user-type-pop-up: Fixed bug for pop-up not appea…
  behind-the-veil-siteroot/imports/ui/components/pages/messages/MessagesPage.jsx
Labels: bug, conflict

#131 Feature/86cw91pmv payment receipt
  behind-the-veil-siteroot/imports/api/collections/receipts.js
  behind-the-veil-siteroot/imports/api/methods/receipts.js
  behind-the-veil-siteroot/imports/ui/components/DatabaseHelper.jsx
  behind-the-veil-siteroot/imports/ui/components/pages/request-booking/PaymentDetails.jsx
Labels: bug, conflict

#141 Feature/86cuwgm4g display review ratings
  README.md
  behind-the-veil-siteroot/imports/api/publications/reviews.js
  behind-the-veil-siteroot/imports/ui/components/DatabaseHelper.jsx
  behind-the-veil-siteroot/imports/ui/components/pages/artist/SpecificArtistPage.jsx
  behind-the-veil-siteroot/imports/ui/components/pages/profile/ArtistProfileTabs.jsx
  behind-the-veil-siteroot/imports/ui/components/pages/profile/artistTabs/ArtistReviewsTab.jsx
  behind-the-veil-siteroot/mockdata/reviews12.json
  behind-the-veil-siteroot/server/main.js
Labels: bug

#132 Feature/86cw9unkw add edit service images db
  behind-the-veil-siteroot/imports/api/methods/images.js
  behind-the-veil-siteroot/imports/api/methods/services.js
  behind-the-veil-siteroot/imports/ui/components/DatabaseHelper.jsx
  behind-the-veil-siteroot/imports/ui/components/pages/service/AddEditServicePage.jsx
Labels: conflict
